### ISSUE TITLE
How to call a script function from C?

### ISSUE THREAD

**Issue by jarroddavis6889** [riicchhaarrd/gsc#18]
Possible?

I need my game library to call into specific routines in script.

Jarrod

**Comment by riicchhaarrd** [comment]
# Writing glue code/wrapper

1. Create your to be exported function

```c
int my_function(vm_t *vm)
{
	int arg = se_getint(vm, 0); //get the first argument to my function from the stack
	
	//you can call your glue/wrapper c function here and return the value to gsc
	//e.g
	//se_addfloat(vm, sinf(se_getfloat(vm, 0));
	//return 1;
	
	if(arg == 1)
		se_addstring(vm, "my message"); //push a string onto the stack
	else if(arg == 2)
		se_addint(vm, 123); //we push integer 123 onto the stack
	else
		return 0; //return 0 means we don't have a return value and null will be pushed onto the stack
	return 1; //return 1 means we have a return value
}
```

2. Add it to a array of type stockfunction_t

```c
stockfunction_t my_function_set[] = {
	{"my_function", my_function},
	{NULL,NULL}
};
```

3. After creating a vm instance (vm_t*) add it to the stock functions with se_register_stockfunction_set

Example of how to create a vm instance: (https://github.com/riicchhaarrd/gsc/blob/master/src/standalone.c#L73)

```c
extern stockfunction_t my_function_set[];
se_register_stockfunction_set(vm, my_function_set);
```

4. Run the VM and call your function
```gsc
main()
{
	value = my_function(1);
	printf("value = " + value + "\n");
	value = my_function(2);
	printf("value = " + value + "\n");
	value = my_function(3);
	printf("value = " + value + "\n");
}
```

# Alternative method using FFI

The exported function from the library has to be in cdecl calling convention and at the moment there's only support for x86.
Use #pragma comment(lib, "/path/to/library") with the path of the library

**Example**

**Windows**
#pragma comment(lib, "msvcrt.dll")

**Linux**
//replace the path with the path to your library that you want to import the C function from
#pragma comment(lib, "/lib/i386-linux-gnu/i686/cmov/libc.so.6")


```gsc
#pragma comment(lib, "msvcrt.dll")

main()
{
	//When there's a conflict and printf is a builtin function of GSC and it exists in the library aswell, the GSC function will be used by default.
	//To combat this, if you put a dollar sign in front it will always call the exported function from the shared library.
	//e.g
	
	printf("Hello world\n"); //builtin function
	$printf("Hello world\n"); //FFI function
	
	//If the function isn't a builtin function, then omitting is fine too.
	i = atoi("12345");
	printf("i = %\n", i);

	p = malloc(1024);
	$snprintf(p,1024,"%d %s\n", i, "ok");
	$printf("%s", p);
	free(p);
}
```

**Comment by jarroddavis6889** [comment]
Ahh I see, wonderful thanks so much. Maybe make this info a wiki entry or something.
